### ISSUE TITLE
9주차 수행목표

### ISSUE THREAD

**Issue by red-Pen9uin** [2021-Dev-Study/Algorithm#54]
## 💢 분량 : **07단원_문자열** 
> `2022-02-15` ~ `2022-02-21`

### ✏ 백준
> **`[단계별로 풀어보기]`** - **`브루트 포스`** 
>***[백준]*** **`[전체]`** - 「옵션 : **`문자열 or 브루트포스법 or kmp or 보이어-무어 다수결 투표 `** & **`실버 3`** & **`제출 - 10000회 이상`** 」 **검색** - "한국어"문제만
- **총 12 문제**

**Comment by yummygyudon** [comment]
이번 PR 때
나중에 기본수학 1, 2 혹시나 별도로 하실분들이 있을듯해서
폴더 만들어놨습니당!!
